### PR TITLE
Interface

### PR DESCRIPTION
**Pull request by louipc**
This is the beginning of more work to make the interface more configurable.
First patch is for whitespace only to change some lines that had tabs instead of spaces.
Second patch makes the action indicators like <--, -->, -!- configurable

### CODE REVIEW

**Comment by JFreegman** [comment]
There's a bit of a problem with this. Chat scrolling depends on knowing the exact length of each line, including those `-->` symbols. You'll need to account for this somehow here: https://github.com/Tox/toxic/blob/master/src/line_info.c#L153-L185

**Comment by louipc** [comment]
How does toxic behave without that adjustment? It didn't seem to change anything as far as I could tell, even if I set the length to something longer than 3 characters, which is truncated back to 3 anyways.

But yeah those hardcoded values should be adjusted to be dynamic anyways. Should the CONNECTION message type be split into two types? IN_CONNECTION and OUT_CONNECTION?

Maybe the strlen should be determined after the message output is assembled if possible..

**Comment by JFreegman** [comment]
If the length isn't correct It will sometimes not scroll the window down when it should if the message is a certain length. This might only happen 1% of the time.

Those hardcoded values just account for things like the space between your name and the message or newlines. Nothing dynamic.

**Comment by louipc** [comment]
Ok. Ready for another review.

**Comment by louipc** [comment]
Thanks.

**Pull request merged**
