### PR TITLE
Make "Last seen" handle year rollover correctly

### PR DESCRIPTION
**Pull request by flussence**
Happy new year!

My friends list is showing things like "Last seen: -297 days ago" right now. This ought to fix it.

### CODE REVIEW

**Comment by JFreegman** [comment]
First lesson of 2015: The % operator in C does remainder, not modulus. I pushed a simpler fix for this but thanks anyhow. Happy new year!

**Comment by JFreegman** [comment]
On second glance I see that you've taken into account years which I was too lazy to do, I should probably go with your version.

**Comment by flussence** [comment]
Oh, there's one more thing I missed (now that I'm not trying to code at 5am...)

You probably want to remove the `% 365` as well, or it'll never show correct values higher than that. :)

**Comment by JFreegman** [comment]
Done.

**Pull request merged**
